### ISSUE TITLE
Random URL Example Failing

### ISSUE THREAD

**Issue by katerberg** [dareid/chakram#1]
When I try to run the example test from the `README.md` using Chakram v0.0.3, I get an error on the valid email address test.

![screen shot 2015-04-28 at 2 55 42 pm](https://cloud.githubusercontent.com/assets/479643/7378919/8cbe1bbe-edb6-11e4-865d-55d5160d8558.png)

It appears there is an issue with a function being passed as the test condition for `json()`.

**Comment by dareid** [comment]
That example included functionality added in version 0.1.0 - I will have to be more careful with configuration management going forward. 
I have updated NPM to version 0.1.0, along with the documentation website. Sorry for the inconvenience, hopefully it should now be working - feel free to reopen if not.

**Comment by katerberg** [comment]
Looks great after going to 0.1.0. Thanks!
