### ISSUE TITLE
chakram.get(url,params) can't pass the params into url

### ISSUE THREAD

**Issue by xwmyth8023** [dareid/chakram#115]
`var chakram = require('chakram'),
expect = chakram.expect;

describe("Minimal example", function() {    
it("should provide a simple async testing framework", function () {
    var pa = {'show_env':1};
    return chakram.get("http://httpbin.org/get",pa)
    .then(function(response){
        console.log(response.body);
        expect(response).to.have.status(200);
        return chakram.wait();
    })
});
});`
**Result:**
  Minimal example
{ args: {},
  headers:
   { Accept: 'application/json',
     Connection: 'close',
     Host: 'httpbin.org' },
  origin: '152.101.38.249',
  url: 'http://httpbin.org/get' }

The params 'pa' didn't write into the url

**Comment by hom3chuk** [comment]
`params` are coming from [request library](https://github.com/request/request#requestoptions-callback), thus query string parameters should go under `qs` field:

<pre><code>
  let params = {
    headers: {
      'Authorization': 'Bearer ' + user.token,
      'Prefer': 'return=representation'
    },
    <b>qs: {'limit': 2}</b>
  }

  return chakram.get(
    host + route.some,
    <b>params</b>
  ).then(r => {
    console.log(r.response.request.href)
    expect(r).to.have.status(200)
    expectCollection(r)
    return r.body[0]
  })
</code></pre>

This snippet comes from the real test suite, so omit some fluff like headers and custom `expect`s. It logs to the console:
<pre><code>
http://localhost:3000/some<b>?limit=2</b>
</code></pre>

cc @dareid you can close this one 🤓
