### ISSUE TITLE
[Question] Is there way to post XML data?

### ISSUE THREAD

**Issue by suin** [dareid/chakram#12]
I'm testing an API which accepts XML data on POST method.
Is it possible to post XML data by chakram?

**Comment by dareid** [comment]
The library is designed for JSON APIs, but it is still possible to post XML.
So when you call the chakram methods you need to pass a json option which is set to false (the default is true). Then set the data argument of the chakram.post to the string or buffer containing the XML data you wish to send.
A relevant test can be seen at https://github.com/dareid/chakram/blob/master/test/methods.js#L17 which posts a non json string.

**Comment by dareid** [comment]
Oh and you will probably need to set the content-type request option, see https://www.npmjs.com/package/request#request-options-callback

**Comment by dareid** [comment]
I will assume this question is closed. Please feel free to reopen if you would like to ask anything else. Thanks for the question!

**Comment by katerberg** [comment]
For future reference, the methods test now lives here: https://github.com/dareid/chakram/blob/master/test/core/methods.js

**Comment by gboorse** [comment]
Ran into this issue myself and ended up with something like this:

```
const response = await chakram.put(myUrl, myXml, {
    // chakram requires this setting if not sending JSON
    json: false,
    headers: { 'Content-Type': 'application/xml' },
  });
```
