### ISSUE TITLE
I want to get status code

### ISSUE THREAD

**Issue by Puneet21** [dareid/chakram#122]
I am writing a test case with Before After. So in After I want some code to be executed only if that particular test case got passed so for that I want to put an if condition in After block saying if status code is 200 then execute this. How to get this status code while using chakram.

after -
If(statusCode ==200)
{}

how to get this status code. I tried number of ways to get that but everytime it shows undefined.

**Comment by BanuPrashanth** [comment]
const statusCode = async () =>{
const response = await chakram.get(url, options);
console.log(response.statusCode)
}
