### ISSUE TITLE
[Question] Is it possible to still use the done callback of mocha in it blocks?

### ISSUE THREAD

**Issue by basco-johnkevin** [dareid/chakram#13]
I wonder how could I test a code the uses callbacks instead of promises like below:
```
describe('with valid params', function() {
  it('should create a ticket', function () {

    // ... removed code

    return chakram
      .post(API_URL + '/tickets/', payload, options)
      .then(function(response) {

        // check that the ticket has been saved to the db
        Ticket.find({where: {id: 1}}, function() {
          expect(ticket.subject).to.equal(payload.subject);
        });
      });
  });
});
```
The test above will always pass even if it doesn't meet this expectation `expect(ticket.subject).to.equal(payload.subject);` .

I tried changing it to: `expect(ticket.subject).to.equal('notTheExpectedSubject');` and it still passes. If using the done() callback is possible, I can just add it below the expectation. I tried it but for some reason the test becomes flaky.

Using promises works and its not flaky:
```
return Ticket.find({
  where: {
    id: 1
  }
}).then(function(ticket) {
  expect(ticket.subject).to.equal(payload.subject);
});
```

I'm curious how to make it work using callbacks though.

**Comment by dareid** [comment]
Chakram does support `done` callbacks, however the main aim is promises, as such the only test I can point you to is https://github.com/dareid/chakram/blob/master/test/base.js#L29. 

Essentially remove all promise returns from the `it`. Then add the `done` argument and call `done` after your expect(ticket.subject) assertion. Something like this should work:

```
describe('with valid params', function() {
  it('should create a ticket', function (done) {

    // ... removed code

    chakram
      .post(API_URL + '/tickets/', payload, options)
      .then(function(response) {

        // check that the ticket has been saved to the db
        Ticket.find({where: {id: 1}}, function() {
          expect(ticket.subject).to.equal(payload.subject);
          done();
        });
      });
  });
});
```

Let me know if you have problems and I can bolster the tests to ensure it is correctly handled.

**Comment by basco-johnkevin** [comment]
@dareid I'm not sure why, but that does work "sometimes". It's very flaky. That's why I asked if its really possible to use the done() callback. I'll try to give more info later.

**Comment by dareid** [comment]
That would be brilliant, thanks. If you could reproduce the problem with a minimal example that would be helpful, I could then put it into the tests as well. (I am still working on your other issue btw :) )

**Comment by dareid** [comment]
Any luck reproducing the issue? I was wondering if you could share the removed code to give some context?

**Comment by basco-johnkevin** [comment]
@dareid I noticed that it also happens when I use promises. So I guess its an issue in my code somewhere, not in chakram. It only happens in one of our `it` block. I'll give you an update once I figure out what's the cause of the issue.

**Comment by dareid** [comment]
I will close this issue for now. Please feel free to reopen if the problem has not been resolved.
