### ISSUE TITLE
Better error output when testing json schema via tv4

### ISSUE THREAD

**Issue by tbazelczuk** [dareid/chakram#14]
Please provide more information about error given by tv4 lib. Current implementation gives only general information about the error. Please concat some major information like dataPath, schemaPath. This would be very useful.

```javascript
this.assert(
    valid,
    'expected body to match JSON schema '+JSON.stringify(schema)+'. error: ' + tv4.error.message + ' ' + tv4.error.dataPath + ' ' + tv4.error.schemaPath,
    'expected body to not match JSON schema ' + JSON.stringify(schema)
);
```

**Comment by dareid** [comment]
Thanks for the suggestion, this has been implemented in 1.0.1.
