### ISSUE TITLE
Can't add JSON schema before assertion

### ISSUE THREAD

**Issue by stianborgesen** [dareid/chakram#19]
Shakram supports validating JSON schema by doing something like this:

"expect(getRequest).to.have.schema(jsonData, jsonSchema);"

This works fine. But how do I add other JSON schemas besides the 'jsonSchema'? Let's say my 'jsonData' holds a reference to another jsonSchema, according to the tv4(underlying JSON schema validator) documentation this must be done before a call to the validation function. When using tv4 with Chai one can do the following to add a JSON schema to the validator before validating:

chai.tv4.addSchema('url',schema);

But how can I do this when using Chakram? I think it is a matter of getting the chai or tv4 instance extended by Chakram. Then i could do as above. I can't figure out how to get it. This should be documented somewhere.

The chakram instance has a chai property, but is has a null value. This seems odd to me.

**Comment by dareid** [comment]
Thanks for the issue. Unfortunately I won't have time to look at it until the weekend.

**Comment by dareid** [comment]
Hopefully version 1.1.0 will allow you to register schemas. I have added a test as well demonstrating the functionality. 
I will close this issue. If this does not solve the issue please feel free to reopen. 
Thanks again for the issue.
