### ISSUE TITLE
get response properties

### ISSUE THREAD

**Issue by octavianmiu** [dareid/chakram#20]
I want to send a email with status code, response format.
how do i get them? ex. : var = response.statusCode

**Comment by dareid** [comment]
This is the response from chakram calls http://dareid.github.io/chakram/jsdoc/global.html#ChakramResponse. Maybe that will help. If not, could you describe your problem in more detail?

**Comment by octavianmiu** [comment]
my problem is quite simple. chakram is making some checks to detect if a request finishes with success. It this doesn't happens i need to get the error codes lice status code or json response if it s the case

**Comment by dareid** [comment]
The documentation I have linked before details the response from the chakram library, this contains the body and returned status code. An example of using this can be found at https://github.com/dareid/chakram/blob/0b5703ba59c63604f24083e35a8629fce454c106/test/methods.js#L11

**Comment by dareid** [comment]
I am going to close this issue as I think an answer has been provided. If that is not the case, feel free to reopen with additional information.

**Comment by skolsuper** [comment]
I am having a similar problem, just started a fresh project, installed chakram, use the example `define` block and change the url for the request, `request.body` is undefined.  The url I changed it to certainly has a body, I have verified with curl.

I think it might be related to [this](http://stackoverflow.com/a/23509939/2347231), something to do with the body not being parsed?

**Comment by skolsuper** [comment]
Some code:

```javascript
it('should log in ', () => {
    var response = chakram.post(conf.paths.base + 'signin/', {username: 'test', password: 'test'});
    expect(response).to.have.status(200);
    expect(response).to.have.header('Content-Type');
    expect(response).to.have.json('apiName', 'ObtainJwtToken');
    expect(response.body).to.be.undefined;
    return chakram.wait();
  });
```

This test passes.
