### ISSUE TITLE
Setting global defaults for the request module used by chakram

### ISSUE THREAD

**Issue by johneke** [dareid/chakram#21]
How do I set global defaults for the request module used by chakram?

**Comment by dareid** [comment]
Currently I do not think this is possible. However, I will add in the capability next weekend hopefully.

**Comment by johneke** [comment]
Great!! Thanks @dareid!

**Comment by dareid** [comment]
Hopefully version 1.2.0 addresses your need, if not, pleased feel free to reopen the issue. Sorry for the lateness.

**Comment by johneke** [comment]
Great! Thanks a lot @dareid! I'll give it a try
