### ISSUE TITLE
JSON cannot compare null value

### ISSUE THREAD

**Issue by WhiteFur** [dareid/chakram#24]
```expect(response).to.have.json("result", null);```
always results in
Error: could not find path 'result' in object {"result": null}

I found that the path value with null is taken as an error.

lib/utils/objectPath.js
```
if(subObject === undefined || subObject === null) {
            throw new Error("could not find path '"+path+"' in object "+JSON.stringify(obj)); 
        }
```

**Comment by dareid** [comment]
Good catch, I will try to address this weekend. Thanks for the issue
