### ISSUE TITLE
How do I send multipart/form-data using chakram

### ISSUE THREAD

**Issue by johneke** [dareid/chakram#26]
I tried following the requestjs way of doing it, but it didn't work:
```
chakram.request('POST', '/path/to/my/url', {formData: {'file': fs.createReadStream('/path/to/file')}});
```
Cant seem to figure it out using the docs either. Could you let me know how I can do this?

Thanks!

**Comment by dareid** [comment]
I have added a test which hopefully demonstrates the capability : 46f733f4529960d5abaa8f857c890c4e43a925a8. I will close this issue, but feel free to open again if it has not helped. I am also available to discuss on gitter if required.
