### ISSUE TITLE
How to pass variable in chaining URL

### ISSUE THREAD

**Issue by jagdeepjain** [dareid/chakram#29]
post('/login', {"user" : "user1", "password": "password"}) This will return the user 'userId' and this id will be inserted in to next get request.

get(/user/{userId}/requests) 

How to pass userId in above get request, dyanmically?

**Comment by dareid** [comment]
Hopefully our conversation in gitter has resolved this. Feel free to reopen if not.

**Comment by jagdeepjain** [comment]
Yes it does :) Thanks for quick response.
