### ISSUE TITLE
Debug logging of requests

### ISSUE THREAD

**Issue by dareid** [dareid/chakram#30]
For debugging would be useful to log the request and response received. Should support per request logging and default logging for all requests.

**Comment by art-tykh** [comment]
This is very useful feature. Cannot wait for it to be implemented.

**Comment by edvinlinden** [comment]
I agree, this would be a great feature!

**Comment by dareid** [comment]
This could be potentially achieved using https://github.com/request/request-debug

**Comment by dareid** [comment]
Guys, just committed an initial approach to debugging. If you could try it out and see what you think before I push to NPM. See https://github.com/dareid/chakram/blob/e206665307150bd4d13300238307808ca6891c1b/lib/debug.js for details of the two new methods on the chakram object.

**Comment by dareid** [comment]
Deployed in v1.3.0

**Comment by garethmcc** [comment]
Is there anyway to make it expand out all objects? As per my example below I get just the type identifier of Object not the actual expanded object:
`{ response: 
   { debugId: 1,
     headers: 
      { 'content-type': 'application/json',
        'access-control-allow-origin': '*',
        vary: 'origin',
        'cache-control': 'no-cache',
        'content-length': '541',
        'accept-ranges': 'bytes',
        date: 'Tue, 09 May 2017 13:30:32 GMT',
        connection: 'close' },
     statusCode: 200,
     body: 
      { total: 1,
        count: 1,
        page: 1,
        perpage: 10,
        cache: false,
        items: [Object] } } }
`

**Comment by dareid** [comment]
you can specify the logging function to use as an argument to start debug, see http://dareid.github.io/chakram/jsdoc/module-chakram.html#.startDebug. This way you can adjust to log what ever information is important to you.

If you come across a logging function which is generally useful feel free to raise a PR :)
