### ISSUE TITLE
tests fail when accessing a https server with self-signed certs

### ISSUE THREAD

**Issue by MarceloEmmerich** [dareid/chakram#31]
I tried passing ``params`` like this to ``chakram.get()`` but it did not work:
```JavaScript
var params = {
    agentOptions : {
        key: fs.readFileSync('key.pem'), 
        cert: fs.readFileSync('cert.pem')        
    }
}
```

**Comment by MarceloEmmerich** [comment]
happy to fix it myself if you point me in the right direction

**Comment by dareid** [comment]
Thanks for the issue. Chakram relies on request for these sort of things, so all I can do is point you towards the request documentation. In particular https://github.com/request/request#using-optionsagentoptions, and the agentOptions.ca option possibly?

**Comment by MarceloEmmerich** [comment]
ok no problem. Will fork and try to fix myself and issue a pull request if succeeded.

**Comment by dareid** [comment]
Did you try passing the agentOptions.ca option? That shouldnt require any changes to Chakram

**Comment by MarceloEmmerich** [comment]
Ok, this worked for me in the end:

set ``process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`` at the beginning of the test file and use pass my self signed key and cert like this:
```javascript
var config = {
    agentOptions: {
        key: fs.readFileSync('key.pem'), 
        cert: fs.readFileSync('cert.pem'),
        securityOptions: 'SSL_OP_NO_SSLv3' 
    }
}
var response = chakram.get("https://localhost:8000", config );
```

**Comment by dareid** [comment]
Brilliant, glad you got it sorted :)
