### ISSUE TITLE
Schema tests pass even if the schema has invalid $ref's

### ISSUE THREAD

**Issue by Bartvds** [dareid/chakram#32]
I was refactoring my JSONSchema and messed up the internal $ref's (like `#/definitions/foo`), but the tests still pass. 

Turns out this is behaviour from TV4 that returns `true` for validation even if the schema cannot resolve some of it's references. The TV4 docs note:

> If schemas are referenced ($ref) but not known, then validation will return true and the missing schema(s) will be listed in tv4.missing.

This seems like an odd choice, since it makes the test brittle and prone to break silently (unless you test your tests).

Maybe chakram should also check for this `missing` attribute?

**Comment by dareid** [comment]
Thanks for the pull request. Quite related to #27. 
I am a bit disappointed how TV4 deals with invalid and missing schemas. It may be worth evaluating alternative JSON schema validation libraries in the future.

**Comment by dareid** [comment]
This may be a suitable library to adopt - https://github.com/epoberezkin/ajv. It seems to validate the schema before validating the object.
