### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by art-tykh** [dareid/chakram#42]
Link to [documentation](http://dareid.github.io/jsdoc/url) from **[Getting Started](http://dareid.github.io/chakram/)** section is broken.
<img width="550" alt="screen shot 2016-03-21 at 11 23 28 am" src="https://cloud.githubusercontent.com/assets/1598859/13914644/59f4f8d4-ef58-11e5-9004-b43f625f5df4.png">

**Comment by dareid** [comment]
Thanks for letting me know :)
