### ISSUE TITLE
How can set request headers?

### ISSUE THREAD

**Issue by caihaoyu** [dareid/chakram#46]

**Comment by quidcomobile** [comment]
I'll agree on this one, is it possible to pass headers in get like that 

chakram.get('url' , BODY, HEADERS)

**Comment by dareid** [comment]
Chakram uses the request library. As such headers can be sent by defining them in the request options object. See the documentation at http://dareid.github.io/chakram/jsdoc/module-chakram.html#.get .

So for example:
```
var requestPromise =  chakram.get("http://httpbin.org/delay/1", {
   headers: {
      'User-Agent': 'request'
   }
});
```

**Comment by alexandros-s** [comment]
It's actually 

      let requestData = {
        "username": "testuser+13@testmail.com",
        "password": "testpass"
      };

      let options = {
        headers : service.HEADERS
      };

      response = chakram.post(URL, requestData, options);

**Comment by caihaoyu** [comment]
thinks
