### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by reidlaiatags** [dareid/chakram#47]
is there any way to set proxy in chakram module?

**Comment by dareid** [comment]
Chakram uses the request module for HTTP requests. Please have a look at the request options here: https://github.com/request/request#requestoptions-callback.
It seems like there is a `proxy` option. This option can be specified in the options provided to the chakram request methods.
Let me know how you get on

**Comment by dareid** [comment]
Due to lack of activity I will assume the request proxy settings were sufficient

**Comment by reyou** [comment]
@dareid sorry to bump up closed ticket but can you give an example how to pass proxy setting to chakram?

**Comment by Zordid** [comment]
Please reopen this issue. It is a PAIN and simply does not work. I tried to supply options, but 
a) it did NOT work at all
b) this is NOT the correct approach. I need to run these tests from behind proxies AND without proxies. Thus, the program (test definition) should not be different. There must be a global switch for the whole test suite to adhere to some proxy settings properly, without having to alter the code.
