### ISSUE TITLE
[Question] How do you build a request using basic auth

### ISSUE THREAD

**Issue by mtaylorSF** [dareid/chakram#49]
Can someone help out, i'm trying to add basic auth to a request

```javascript
var chakram = require('chakram');
    expect = chakram.expect;
    
var requestHeader = {
      "Authorization": "Basic xxxx",
    };

describe("Chakram", function() {
    it("should provide HTTP specific assertions", function () {
        var response = chakram.get("<host>", requestHeader);
        return expect(response).to.have.status(200);
    });
});
```

Thanks

**Comment by yhuard** [comment]
As [mentioned in the docs](https://dareid.github.io/chakram/jsdoc/module-chakram.html#.get), the second parameter of `chakram.get` corresponds to additional [request options](https://github.com/request/request#requestoptions-callback)

You can authenicate with either:

```javascript
var options = {
    headers: {
        'Authorization': 'Basic xxxx'
    }
};
```

or:

```javascript
var options = {
    auth: {
        user: 'yourusername',
        password: 'yourpassword'
    }
};
```

And then call `var response = chakram.get("<host>", options);`.

**Comment by mtaylorSF** [comment]
Thanks for the example, it works.
