### ISSUE TITLE
JSON schema validation always returns true

### ISSUE THREAD

**Issue by syed12304** [dareid/chakram#50]
Trying to do JSON schema validation and it always returns true.

**response** contains the actual JSON response.
**expectedSchema** contains the expected schema structure

Below is the assertion code:
 expect(response.body).to.have.schema(expectedSchema);

Executed the above code by providing the improper schema structure but still the assertion gets passed.

**Comment by dareid** [comment]
Thanks for the issue. Could you provide the schema and the JSON you are validating?

**Comment by syed12304** [comment]
hi,

below is the sample code

var chakram = require('chakram'),
expect = chakram.expect;

// Schema for a source
var expectScheme = {
        
        Host : {type: 'string'},
        origin : {type: 'string'},
        link : {type: 'string'}      
};

// describe defines the test suite

describe("Chakram", function() {
it("should check that the returned JSON object satisifies a JSON schema", function () {

    return chakram.get("http://httpbin.org/get").then(function(response){
             
        // Displaying the response body of Get call
        console.log(response.body);
       expect(response).to.have.schema(expectScheme);
    })
});
});

Response:

![image](https://cloud.githubusercontent.com/assets/17019200/15499880/f3079070-21c3-11e6-8f55-b9187e0d84b2.png)

If you see the response schema and the expected schema are not the same.

Please let me know if I am missing anything

**Comment by dareid** [comment]
Thanks for the additional information. I am work at the moment, but will try it out later.
One thing to try:  
```
var expectScheme = {
    type: "object",
    properties: {
       Host : {type: 'string'},
       origin : {type: 'string'},
       link : {type: 'string'},
   },
   required: [
      'Host',
      'link',
      'origin'
   ]
};
```

**Comment by syed12304** [comment]
![image](https://cloud.githubusercontent.com/assets/17019200/15503141/b73ac3fc-21d5-11e6-9b8b-48f490197d0c.png)

Thanks for the quick response. Looks like validation fails, if the required set property is not matching the schema..

Please let me know why we need to use **required** set... it is required for schema assertion?

**Comment by dareid** [comment]
Yes validation will fail. We are saying `Host`, `link` and `origin` are required in the response. Which they are not. I was trying to demonstrate that schema validation always passes as the issue suggests.

**Comment by dareid** [comment]
Your examples you sent pass as you have not got that required field. The schema is valid for the response received.

**Comment by syed12304** [comment]
so you mean required set should be defined for the schema validation?

**Comment by syed12304** [comment]
tnx  dareid..

**Comment by syed12304** [comment]
how can we validate the data type is returned properly or not...

// Schema for a source
var expectSchema = {

      created_at: {type: 'string'},
        created_by: {type: 'number'},
        description: {type: 'string'},
   
   required: [
      'description',
      'created_by',
   ]
};

in my response, created_by value is string  but still the assertion gets passed.

**Comment by dareid** [comment]
Could you provide the JSON which is incorrectly passing your defined schema above?

**Comment by syed12304** [comment]
{ created_at: '2016-05-11T15:29:58Z',
  created_by: 'abc',
  description: 'Created......',
  properties: null }

**Comment by dareid** [comment]
So your schema is incorrect. It should be something like this:
```
var expectScheme = {
    type: "object",
    properties: {
       created_at: {type: 'string'},
       created_by: {type: 'number'},
       description: {type: 'string'}
   },
   required: [
      'description',
      'created_by'
   ]
};
```
Maybe have a read through the documentation http://json-schema.org/

**Comment by syed12304** [comment]
Got it.. Tnx for the resolution and timely support

**Comment by rahulmr** [comment]
hello @dareid , I need help for schema validation, could you please guide me on this. I tried the example above still always get the test passed. I want to change the `expectedSchema` in such a way that it should fail the test.

Here is the `expectedSchema `and actual result.

Actual Result (an array) : 
```
[
  {
    "giftCardConfigurationId": 2,
    "applicableFeeName": "Admission Fee",
    "promotionPercent": 100,
    "generationLimit": 2,
    "active": true
  },
  {
    "giftCardConfigurationId": 4,
    "applicableFeeName": "Admission Fee",
    "promotionPercent": 100,
    "generationLimit": 1,
    "active": true
  }
]
```

Expected Schema ::
```

var expectedSchema = {
    "type": "array",
    "properties":
    {
      "giftCardConfigurationId": { "type": "number" },
      "applicableFeeName": { "type": "number" },
      "promotionPercent": { "type": "number" },
      "generationLimit": { "type": "number" },
      "active": { "type": "number" }
    },
    "required": [
      "giftCardConfigurationId",
      "applicableFeeName",
      "promotionPercent",
      "generationLimit",
      "active"
    ]
  };

```

**Comment by rahulmr** [comment]
Got the solution - Posting solution in case anyone else needs it.
Here is the link where you can convert the data to JSON schema with required fields.
http://jsonschema.net/
