### ISSUE TITLE
Issue with schema validation

### ISSUE THREAD

**Issue by syed12304** [dareid/chakram#53]
I have provided the schema as follows:

var expectSchema = {
    type: "object",
    properties: {
       Host : {type: 'string'},
       origin : {type: 'string'},
       link : {type: 'string'},
   },
   required: [
      'Host',
      'link',
      'origin'
   ]
};

I get the below error:

 1) Chakram Validate the returned JSON schema:
    AssertionError: expected body to match JSON schema {
 "type": "object",
 "properties": {
   "Host": {
     "type": "string"
   },
   "origin": {
     "type": "string"
   },
   "link": {
     "type": "string"
   }
 },
 "required": [
   "Host",
   "link",
   "origin"
 ]
.
----
error: Invalid type: undefined (expected object).
data path: .
schema path: /type.
   
........................pm ERR! Test failed.  See above for more details.

Any thought about the error?

**Comment by dareid** [comment]
Could you provide the data structure you are validating

**Comment by syed12304** [comment]
This is the schema:

var expectSchema = {
  "type":"object",
  properties: {
     created_at: {type: 'string'},
     created_by: {type: 'number'},
     description: {type: 'string'}
 },
 required: [
    'description',
    'created_by'
 ]
};

JSON Response to validate:
{ collaborators: null,
  created_at: '2016-05-11T15:29:27Z',
  created_by: '************',
  description: 'Source edited by Test',
  name: 'abc',
  
  updated_at: '2016-05-11T15:29:27Z',
  updated_by: '**********' }

**Comment by harryrose** [comment]
@syed12304 Looking at your schema, you've stated that created_by is a number, but in the object you're  passing, created_by is a string.  Failing JSON schema validation in this case is expected behaviour, therefore I will be closing this issue.  If you think this demonstrates a problem/shortcoming with chakram, please feel free to reopen.

**Comment by syed12304** [comment]
changing the created_by schema as string also returns the same error...

**Comment by dareid** [comment]
what error are you getting?

**Comment by syed12304** [comment]
error: Invalid type: undefined (expected object).
data path: .
schema path: /type.

........................pm ERR! Test failed. See above for more details.

**Comment by asosa9991** [comment]
Could you please advise how this issue was resolved?

**Comment by skhromchenko** [comment]
Did anyone get this issue resolved?

**Comment by Wilt** [comment]
If you get undefined, most likely your response object is empty.
Maybe you get a 401 (Unauthorized) response with an empty (so undefined) body.
