### ISSUE TITLE
JSON response validation with expressions

### ISSUE THREAD

**Issue by syed12304** [dareid/chakram#54]
Does Chakram support for expressions in json response validation.

My requirement is the response object value can be provided as expressions.

For example data property value changes from creation time to time. Can I provide the format in the json to validate it.

Next the user can have any of the multiple values for example the created_by can be admin, superadmin or user..

**Comment by harryrose** [comment]
Hi, @syed12304.  I'm not sure I fully understand your question.  Ideally, your tests will be developed such that you know the response you're expecting. You can then test the output is what you expected to receive.  For example, see the tests in https://github.com/dareid/chakram/blob/master/examples/randomuser.js

**Comment by dareid** [comment]
I am going to close this due to inactivity, please feel free to reopen
