### ISSUE TITLE
intranet url proxy access issues

### ISSUE THREAD

**Issue by jeychan12** [dareid/chakram#57]
We are trying to perform api test using local intranet rest service url with chakram npm module but we are getting issues like below.

Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test. 

we don't have any clue to resolve the issue and there is no specific errors in the console. Could you guide us on this?

**Comment by Senkyryky** [comment]
Try to extend timeout like this:

var chakram = require('chakram'),
     expect = chakram.expect;

describe("test", function () {
    it("should get 200", function () {
        **this.timeout(5500);**
        var response = chakram.get("https://yourapi.api);
        expect(response).to.have.status(200);
        return chakram.wait();
    });
});

**Comment by jeychan12** [comment]
Tried by increase the timeout to 30 seconds but still getting the same failure. Addition to my above question, we are hitting insecure https url(un certified).

**Comment by dareid** [comment]
Any chance you could send some example code? What is your proxy setup?

**Comment by dareid** [comment]
Due to inactivity I will close this issue. If you could provide any code to help diagnose please feel free to reopen.
