### ISSUE TITLE
setRequestDefaults and clearRequestDefaults

### ISSUE THREAD

**Issue by chrisvidal** [dareid/chakram#59]
Im not sure how to use this 2 methods.
I have 2 .js file, one testing the user authenticated scenario and the other one testing a non authenticated user.

in the 1st, i set a default header in the request like this :
````javascript
              chakram.setRequestDefaults({
                headers :  {
                  'Content-Type': 'application/json',
                  'Authorization': 'Bearer ' + token
                }});
````
Then in my second test file, i try to reset it to with 
````javascript
      chakram.clearRequestDefaults();
````

but when i check the header in the further request, the header is still set with my authorization token.

What did i do wrongly ?

**Comment by dareid** [comment]
That looks correct. You can see the tests for this functionality at https://github.com/dareid/chakram/blob/master/test/core/methods.js#L95.

Are you calling `setRequestDefaults` and `clearRequestDefaults` within a `before` hook? Or is it within a `describe`. 

Could you share a larger example?

**Comment by chrisvidal** [comment]
Thanks @dareid for your reply
the set is done inside a before() because i need to get the token back.
the clear is actually

here is the code involved
````javascript
describe("Authenticated  User Scenarios", function() {
describe("Authenticate a User", function() {
      before(function () {
          apiAuthenticatedResponse = chakram.post(url, CREDENTIALS)
          .then(function (apiAuthenticatedResponse) {
              token = apiAuthenticatedResponse.body.data.token;
              chakram.setRequestDefaults({
                headers :  {
                  'Content-Type': 'application/json',
                  'Authorization': 'Bearer ' + token
                }});
              return apiAuthenticatedResponse;
          })

      });
});
````

in the other file, the code is
````javascript
describe("Not Authenticated  User Scenarios", function() {
describe(" Not Authorized User Profile API", function() {
      var apiResponse;
      chakram.clearRequestDefaults();

      before(function () {
...
````

**Comment by dareid** [comment]
So if that is all run in the same mocha process, the code within the `describe` blocks run immediately. So `clearRequestDefaults` will run immediately. Then the `setRequestDefaults` will be called once the `Authenticate a User` tests are run.

So I think to solve it you should put the `clearRequestDefaults` into the `before` of the `Not Authorized User Profile API` describe block.

**Comment by chrisvidal** [comment]
alright, thanks, it works as you described, thanks again

**Comment by ankit-lab** [comment]
Hi Dareid, I don't know how to pass token in chakram, can you share me some examples where you have used token, headers, parameters, etc it will be very helpful for me. Also how to pass body in post and get request

Thanks,
Ankit
