### ISSUE TITLE
JSON include assertion doesn't work

### ISSUE THREAD

**Issue by m1r4ge** [dareid/chakram#6]
The following test always passes:

    it('always passes', function() {
        expect({body: {a: 1, b:2}}).to.include.json({a:1});
        expect({body: {a: 1, b:2}}).to.not.include.json({a:1});
    });

**Comment by dareid** [comment]
Thanks for the issue! 
Hopefully this commit solves the problem. The chai plugin I was using for subset matches didn't take into account not flags, leading to the issue. This plugin has been switched to one which does support not.
A test has been added to verify this.
Travis seems to be down at the moment, so I will upload to NPM early tomorrow as version 0.1.1.
Thanks again.

**Comment by dareid** [comment]
Version 0.1.1 is up on NPM which should fix this issue.

**Comment by m1r4ge** [comment]
Hello, Daniel.
Thank you for the quick response, but the problem hasn't been solved completely.
1) The diff highlighting isn't correct, check this test:

    it('shows incorrect diff', function() {
        expect({body: {a: 1, b:1}}).to.not.include.json({a: 1});
    });

2) If I use a real request to the api, the expectation always passes no mater what json object I place in .json(..) method call.
Let's api returns { email: "test@gmail.com" } then this test will pass without any errors:

    it('passes without any errors', function() {
        var response = chakram.get(apiUrl);
        expect(response).to.have.status(200);
        expect(response).to.not.include.json({});
        expect(response).to.include.json({ email: 'blabla@gmail.com' });
        expect(response).to.not.include.json({ email: 'test@gmail.com' });
        expect(response).to.include.json({ user: 'blabla' });
        return chakram.wait();
    });

By the way, great framework! Thx for your work!

**Comment by dareid** [comment]
Ah sorry that hasn't fixed it. I will look into these issues tonight. 
I appreciate your input, it is important to get these bugs worked out!

**Comment by dareid** [comment]
I have been looking into this with @harryrose. Below is the test case we have been experimenting with. This test should fail 18 times, it actually fails 15 times. The 3 which are passing are related to the include.json assertion.

We are not yet at a conclusion, however it appears like the chai 'include' property used, effects the json assertions. Hopefully we should have a solution shortly.

```js
var chakram = require('chakram'),
    expect = chakram.expect;

describe("Chakram Assertions", function() {    
    
    describe("json", function () {
        describe("fulfilled response", function() {
            var postRequest;
            before(function() {
                postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                return postRequest;
            });

            it("should fail - wait", function () {
                expect(postRequest).to.have.json('json.number', 22);
                return chakram.wait();
            });

            it("should fail after this test", function () {
                expect(postRequest).to.have.json('json.number', 22);
            });

            it("should fail - promise", function () {
                return expect(postRequest).to.have.json('json.number', 22);
            });
        });    

        describe("unfilfilled response", function() {
            it("should fail - wait", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                expect(postRequest).to.have.json('json.number', 22);
                return chakram.wait();
            });

            it("should fail after this test", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                expect(postRequest).to.have.json('json.number', 22);
            });

            it("should fail - promise", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                return expect(postRequest).to.have.json('json.number', 22);
            });
        });   
    });
    
    describe("include json", function () {
        describe("fulfilled response", function() {
            var postRequest;
            before(function() {
                postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                return postRequest;
            });

            it("should fail - wait", function () {
                expect(postRequest).to.include.json('json.number', 22);
                return chakram.wait();
            });

            it("should fail after this test", function () {
                expect(postRequest).to.include.json('json.number', 22);
            });

            it("should fail - promise", function () {
                return expect(postRequest).to.include.json('json.number', 22);
            });
        });    

        describe("unfilfilled response", function() {
            it("should fail - wait", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                expect(postRequest).to.include.json('json.number', 22);
                return chakram.wait();
            });

            it("should fail after this test", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                expect(postRequest).to.include.json('json.number', 22);
            });

            it("should fail - promise", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                return expect(postRequest).to.include.json('json.number', 22);
            });
        });   
    });
    
    describe("status", function () {
        describe("fulfilled response", function() {
            var postRequest;
            before(function() {
                postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                return postRequest;
            });

            it("should fail - wait", function () {
                expect(postRequest).to.have.status(500);
                return chakram.wait();
            });

            it("should fail after this test", function () {
                expect(postRequest).to.have.status(500);
            });

            it("should fail - promise", function () {
                return expect(postRequest).to.have.status(500);
            });
        });    

        describe("unfilfilled response", function() {
            it("should fail - wait", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                expect(postRequest).to.have.status(500);
                return chakram.wait();
            });

            it("should fail after this test", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                expect(postRequest).to.have.status(500);
            });

            it("should fail - promise", function () {
                var postRequest = chakram.post("http://httpbin.org/post", {number: 20});
                return expect(postRequest).to.have.status(500);
            });
        });   
    });
});
```

**Comment by dareid** [comment]
The issue has been traced to the use of a chainable method. The solution will need to ditch the include chainable method. 
Our options are to introduce a new property word to distinguish between exact and subset JSON (however we cannot use include or contains), or an additional argument to the json assertion.

**Comment by dareid** [comment]
Version 1.0.0 replaces the use of include with comprise. JSON subset matches should now be expect().to.comprise.of.json({}). This fixes the issues seen in the test case above. 

In terms of the highlighting, I have opened #8 to cover this. This is a problem with chai subset library which chakram uses.

Again, if this fix does not work, please feel free to reply and I will reopen
