### ISSUE TITLE
Response Time ?

### ISSUE THREAD

**Issue by chrisvidal** [dareid/chakram#60]
Is there a way to get the API response time while testing it ?
would be nice addon

**Comment by dareid** [comment]
I just pushed a responsetime assertion, could you have a look and see what you think. Any feedback would be appreciated :)

**Comment by chrisvidal** [comment]
wow, so awesome !
how shall i update with this new version ?

**Comment by dareid** [comment]
At the moment it is not added to npm whilst u have a look.
You can get the latest version using a package dependency on the specific
commit hash. I am on my phone at the moment so can't get the exact form,
but documentation is here
https://docs.npmjs.com/files/package.json#github-urls

**Comment by chrisvidal** [comment]
alright thanks as per you dais, i managed to update with this specific commit updating my package.json like this 
`"devDependencies": {
    "chakram": "dareid/chakram#837e0cc0b9d1b8b84af01c1cf066c7bd2f772467",
    "mochawesome": "^1.4.0"
  }`

**Comment by chrisvidal** [comment]
got an exception during the test:

`
  before(function () {
        chakram.clearRequestDefaults();
        return apiResponse =  chakram.get(testedUrl)
});
`

the test:
`
    it("responseTime should be below 750ms", function () {
        return expect(apiResponse.responseTime).to.exist.and.to.be.at.least(20).and.at.most(750);
      });
`

the exception
`
3) Not Authorized User Profile API responseTime should be below 750ms:
     AssertionError: expected undefined to exist
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at .<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at Object.defineProperty.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at Context.<anonymous> (spec/users/non_authenticated_user_assertions.js:45:51)
`

**Comment by chrisvidal** [comment]
how could i get the responseTime in the report please ?
this is what actually interests my client, to get this responseTime value

**Comment by chrisvidal** [comment]
is the responseTime feature pushed under the last npm version ?

**Comment by dareid** [comment]
Not yet, I will aim to do a release at the weekend
