### ISSUE TITLE
Question: How to obtain a property from body response

### ISSUE THREAD

**Issue by woolter** [dareid/chakram#62]
I don't know how to obtain property value assigned to "importId" from body to print it with console.log or use it for other test case.

This is my response:
{
  state: 'fulfilled',
  value:
  {
    error: null,
    response:
      IncomingMessage {
        -readableState: [Object],
        readable: false,
        domain: null,
        -events: [Object],
        -eventsCount: 4,
        -maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 200,
        statusMessage: 'OK',
        client: [Object],
        -consuming: true,
        -dumped: false,
        req: [Object],
        request: [Object],
        toJSON: [Function: responseToJSON],
        caseless: [Object],
        read: [Function],
        body: [Object] },
     _body: { **importId**: 4591, status: 'OK' }_,
     jar: RequestJar { _jar: [Object] },
     url: 'http://myUrl'
   } 
}

@dareid this is an amazing framework!

**Comment by chrisvidal** [comment]
you can do
````javascript
console.log(response.body);
````

**Comment by woolter** [comment]
Hi, @chrisvidal
If I wrote `console.log("response",response);`
I obtain my first post
and with `console.log("response.body",response.body);`
this is what i see in console
**response.body undefined**

**Comment by woolter** [comment]
This is my .js
![chakram0](https://cloud.githubusercontent.com/assets/12902748/17710046/f75bb95e-63c1-11e6-8254-11ce5b9c7275.PNG)

This is my console
![chakram1](https://cloud.githubusercontent.com/assets/12902748/17710047/f75df566-63c1-11e6-9f68-5c4b2251abeb.PNG)

**Comment by dareid** [comment]
The response is a promise. As such you should be using `then` to get the actual body.
An example from the main website (http://dareid.github.io/chakram/) : 

```
describe("Promises", function () {
  it("should support asserting Biggie's best track", function () {
    var artist = "Notorious B.I.G.";
    return chakram.get("https://api.spotify.com/v1/search?q="+artist+"&type=artist")
    .then(function (searchResponse) {
      var bigID = searchResponse.body.artists.items[0].id;
      return chakram.get("https://api.spotify.com/v1/artists/"+bigID+"/top-tracks?country=GB");
    })
    .then(function (topTrackResponse) {
      var topTrack = topTrackResponse.body.tracks[0];
      expect(topTrack.name).to.contain("Old Thing Back");
    });
  });
});  
```

**Comment by woolter** [comment]
Thanks a lot for your answer!
Now is working.

You can close this question
