### ISSUE TITLE
Question: how to re-use existing code

### ISSUE THREAD

**Issue by chrisvidal** [dareid/chakram#65]
Im struggling to re-use existing before() code or existing test functions mostly because i need to set some data in the initial before() section
Scenario would be something like i need to test all the basic CRUD operation on a object, hence i need every time to get a list of data in order to get an object id then get the object detail by this id.
then i would like to re-use existing test functions to test the headers, status code, responseTime, etc...i try to re-use the example with testWriteMethods(), but i cant figure out how to pass the parameters setup previously in the before() section.

````javascript
/* param is always undefined here because the method is call before the end of the before() section i guess */
var testMethods = function (myParam) { 
        it("should work", function () {
            ....
        });
        it("should also work", function () {
            ....
        });
    };

describe("Endpoints", function () {
   before(function () {
          var reqwest = chakram.get( url );
          return reqwest.then( function(resp) {
             param = resp.body.json.id;
          });
      });

    testMethods( param );
})
````

**Comment by dareid** [comment]
So the `testMethods` usage would have to be in an `it`. All code within a `describe` is ran as soon as the file is loaded I believe.

**Comment by dareid** [comment]
As I have not heard anything, I will close this issue. Please feel free to reopen.
