### ISSUE TITLE
Negation (.not.) doesn't work for custom plugins

### ISSUE THREAD

**Issue by lootek** [dareid/chakram#66]
In the `teapot` plugin on the main marketing website, I changed `expect(notATeapot).to.not.be.a.teapot` to `expect(notATeapot).to.be.a.teapot` and it still passes for me (note the missing `not` in the chain)

As we discussed on gitter, Daniel has found out that
> it is strange because the teapot plugin defined with the old style syntax works
> (https://github.com/dareid/chakram/blob/master/test/core/plugins.js#L48)
> and if I don't use chakram.wait it seems to work...

**Comment by dareid** [comment]
This seems to fail correctly:
```
before(function() {
    chakram.addRawPlugin("teapot", function (chai, utils) {
        utils.addProperty(chai.Assertion.prototype, 'teapot', function () {
            var statusCode = this._obj.response.statusCode;
            this.assert(statusCode === 418, 
                'expected status code '+statusCode+' to equal 418', 
                'expected '+statusCode+' to not be equal to 418');
        });
    });
});
it("should do what it is told", function() {
    var notATeapot = chakram.get("http://httpbin.org/status/200");
    expect(notATeapot).to.be.teapot;
    return chakram.wait();
});
```

This does not fail correctly:
```
before("define teapot", function () {
  chakram.addProperty("teapot", function (respObj) {
    var statusCode = respObj.response.statusCode;
    this.assert(statusCode === 418,
      'expected status code ' + statusCode + ' to equal 418',
      'expected ' + statusCode + ' to not be equal to 418');
  });
});

it("should do what it is told", function () {
  var notATeapot = chakram.get("http://httpbin.org/status/200");
  expect(notATeapot).to.be.a.teapot;
  return chakram.wait();
});
```

**Comment by dareid** [comment]
`a` and `an` are not valid in chains, they are assertions in their own right. You can see from the examples above that only the middle failing one had a `a` in the chain. I will be updating the documentation tomorrow to reflect this.

This raises #7 again, which would have warned about this.
