### ISSUE TITLE
Is there any way to post data string directly?

### ISSUE THREAD

**Issue by albertyou2** [dareid/chakram#67]
My data is encrypted before post .So I need to send the encrypted data string at one time .
I saw the example post data in this way:
...
chakram.post("http://192.168.10.243:10001/manage/region/addstate",{"k1":"v1","k2":"v2",...}) 
...
Is there convenient way to post data string directly in chakram ?

Thank you !
@dareid

**Comment by dareid** [comment]
It is possible to send non JSON data. It involves setting `json` to false in the request options and setting any required content-type headers.
Previous discussion on the topic can be found here https://github.com/dareid/chakram/issues/12

**Comment by albertyou2** [comment]
hi @dareid Thank you for reply !
I have read the issue #12 .
Unfortunately I am very new to mocha and charm and I didn't get the complete solution yet.
1.Do you mean I should post my data as below?

var encryptedDataString = "xxxxxxxxxxxxxxxx"; // my post data 
var response = chakram.post("https://host/path", undefined, {
				formData: {
					pkgFile : encryptedDataString // set my data here 
				}
			});
2.  How to set the header ?
3. What does the NO.2 argument of the post function "undefined" mean?

**Comment by dareid** [comment]
so I suspect it will be like this (untested):
```
var response = chakram.post("someURL", "somenonjsondata", {

**Comment by albertyou2** [comment]
@dareid oK I 'ill try this

**Comment by albertyou2** [comment]
hi @dareid 
I tried this code but got a timeout error:
 var response = chakram.post("http://192.168.10.243:10001/manage/region/addstate", "name=123&creater=331", {
           json: false,
           headers: {
               "content-type":"text"
           }
       });
ERROR is here ===> Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

I also tried this code as below and it worked fine:
var postdata =  {formdata:"name=123&creater=331"}
chakram.post("http://192.168.10.243:10001/manage/region/addstate",undefined,postdata)

**Comment by dareid** [comment]
Ah I did not realise you were sending form data. Glad you got it working. Let me know if you have any other questions.
