### ISSUE TITLE
How to run multiple chakram test files with Mocha

### ISSUE THREAD

**Issue by jeychan12** [dareid/chakram#71]
I have created couple of chakram API test javascript files and run the files using mocha like below.

mocha test1.js
mocha test2.js

When I run individually I am getting proper response. 

But when I run the file in single step by using below command, getting error response.

mocha *.js

Do you have any solution for this?

**Comment by dareid** [comment]
Sorry for the late response. Mocha supports glob type patterns, and should support running both of the files with *.js. 

To provide more help, I will probably need a minimal example of the problem.

**Comment by dareid** [comment]
I will close this issue due to no response.
