### ISSUE TITLE
Wait for all tests to finish

### ISSUE THREAD

**Issue by Syberspace** [dareid/chakram#76]
Hi,
is there a way to wait for all `describe`s to finish before running a piece of code?
Something along the lines of
```js
chakram.waitForEverythingToFinish(function() {
    //code
});
```

I have a couple of describes spread across multiple files for sake of modularization and would like to run a kind of "cleanup" routine after all tests are done.

**Comment by dareid** [comment]
I believe you can use `after` for this. If the `after` block is global, it will run after all the `describe`s. 
Let me know if that works

**Comment by Syberspace** [comment]
yes, that works. 
thank you very much.
