### ISSUE TITLE
is there a flag for disabling ssl certification verification?

### ISSUE THREAD

**Issue by Yukonjess101** [dareid/chakram#78]
Just curious if there is a flag, or another way of disabling ssl certification verification.

Thanks!

**Comment by dareid** [comment]
Not in chakram itself. I believe to change this you would be looking at the node level. A quick google looks to point at the variable `NODE_TLS_REJECT_UNAUTHORIZED`. Does this help?

Sorry for the late response

**Comment by Yukonjess101** [comment]
No problem on the late reply.  I was able to find that node level variable
and will continue to use it.

Thanks for supporting the project!

Jesse Gregory
