### ISSUE TITLE
Getting the vlaues of an array?

### ISSUE THREAD

**Issue by ferylukacs** [dareid/chakram#83]
So i have this simple website that returns: {"key":1,"value":{"name":"Gary","color":"blue","reindeer":true}}

and i am using: 
it("chakram wiat", function(){
		chakram.startDebug();
		var response = chakram.get(url);
                return chakram.waitFor([
		        chakram.expect(response).to.have.status(200),
		        chakram.expect(response).not.to.have.status(404),
		        chakram.expect(response).to.have.header('content-type', 'application/json;charset=UTF-8'),
		        chakram.expect(response).to.have.schema('value', {"required": ["name", "color", "reindeer"]}),
		        chakram.expect(response.body).to.contain[("gardsadsadsary")]		        
		    ]);
	});

The schema comes back as passed, but the body to contain, seems to come back as passed, even if i typa gibberish in the (" "). 

New to chakram, and automation testing. How can i check that it contains the required values?

**Comment by ferylukacs** [comment]
Ok, so i figured it out with: chakram.expect(response).to.have.json('value.name', 'Gary'), but how can i verify all the three items, in one line?

**Comment by codepills** [comment]
@ferylukacs In addition to strings, you can expect the value to be an object. For example:

```
expect(response).to.have.json('value', {name: "Gary', color: 'blue', reindeer: true});
```

**Comment by ferylukacs** [comment]
i had to add a a few ' ' , but it seems it's working. thanks a lot
