### ISSUE TITLE
Handling 302 statuses

### ISSUE THREAD

**Issue by EPICmynamesBG** [dareid/chakram#85]
Hello! I'm trying to implement some testing on an endpoint that upon success performs a redirect. However, it looks like the redirect is getting past chakram and directly loading the page that is redirected to. I'd like to validate the status and the Location header. Is this possible in Chakram, or am I just doing things wrong? Thanks in advance. Code example below.

```javascript
        var loginRequest = chakram.get(url);

        it('should return 302', function(){
          expect(loginRequest).to.have.status(302);
          return chakram.wait();
        });
                
        it ('should redirect to localhost', function(){
          return expect(loginRequest).to.have.header('Location', /(http:\/\/localhost?token=[^\s]{2,})/);
        });
```

**Comment by dareid** [comment]
The request library, which chakram is built on top of, has a few options for controlling redirects. I think `followRedirect` which is by default is `true` needs to be set to `false`. Something like this (untested):

```
        var loginRequest;
        before(function() {
          loginRequest = chakram.get(url, {
               followRedirect: false
          });
          return loginRequest;
        });

        it('should return 302', function(){
          return expect(loginRequest).to.have.status(302);
        });
                
        it ('should redirect to localhost', function(){
          return expect(loginRequest).to.have.header('Location', /(http:\/\/localhost?token=[^\s]{2,})/);
        });
```

**Comment by EPICmynamesBG** [comment]
@dareid That worked like a charm. Thank you! And for future reference, maybe it should be more well noted in the docs that chakram uses the _request_ module for requests, so questions like this can reference the _request_ docs first :smiley:
