### ISSUE TITLE
How do i post using using chakram with body and headers?

### ISSUE THREAD

**Issue by kaustavbasu075** [dareid/chakram#88]
I am getting the below error
 Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by dareid** [comment]
Any chance of some code to look at? Very hard to diagnose without it

**Comment by kaustavbasu075** [comment]
I am trying to get a basic test running,but not being able to.Any help would be appreciated.I have done an npm install for chakram and mocha.Rite now i am getting a 403,but manually and from my rest console,i am getting a 200.For all urls i am getting a 403

**Comment by kaustavbasu075** [comment]
Here is my code:
var chakram = require('chakram'),
expect = chakram.expect;

describe("Chakram",()  => {

    it("should make HTTP assertions easy", function () {
        var response = chakram.get("http://httpbin.org/get?test=chakram");
        expect(response).to.have.status(200);
        return chakram.wait();
    });
});

**Comment by kaustavbasu075** [comment]
Rite now,i have removed the body and headers.Just trying to hit a basic url

**Comment by dareid** [comment]
I am going to close this due to inactivity, please let me know if you are still having issues.

**Comment by Adam-Grz** [comment]
Change the name of this issue - it is not about POST, it is about GET.
