### ISSUE TITLE
Expectation promises not fulfilled

### ISSUE THREAD

**Issue by viveleroi** [dareid/chakram#9]
Using Mocha 2.2.4, chai 2.3.0, chai-as-promised 5.0.0 - following the examples on the documentation, a failed test shows:

        ✓ should have a 200 response status
        1) should have a 200 response status

      1 passing (65ms)
      1 failing

      1) API Tests Create should have a 200 response status:
      Error: Some expectation promises were not fulfilled before the test finished. Ensure you are waiting for all the expectations to run

Running the pure demo code even fails:

    it('should have a 200 response status', function() {
        var google = chakram.get("http://google.com");
        expect(google).to.have.status(200);
    });

If the test is successful, everything works as expected. An error causes the test to show twice in the list, show as both failed and passed.

If we wrap the promise ourselves, it works in both cases.

    it('should have a 200 response status', function(done) {
        response.then(function(result) {
            try {
                expect(result).to.have.status(200);
                done();
            } catch (e) {
                done(e);
            }
        });
    });

**Comment by dareid** [comment]
Chakram will fail tests, in their afterEach hook, if any of the test's expectations are not fulfilled. Expectations are only fulfilled if the test waits for them, this can be achieved by returning a promise from the 'it' block which fulfills once all the expectations have ran. 

In the case above, you are not returning a promise, and hence the test is never actually getting performed. For this reason, the afterEach hook will fail it, which is why you see a success then a failure.
If you change your code to be:
```js
it('should have a 200 response status', function() {
    var google = chakram.get("http://google.com");
    return expect(google).to.have.status(200);
});
```
This should pass and fail correctly. There is also the method chakram.wait(), which will return a promise which will wait for all expectations to complete (in the current scope). 

In test/base.js there is some tests which may be of interest to you. 
If you have any issues I would be happy to help out!

**Comment by twh1808** [comment]
I too am having similar issues. I've tried both suggested examples in this thread, but with no success:
```
it('should have a 200 response status', function(done) {
    var response = chakram.get('http://www.google.com/');

    return expect(response).to.have.status(200);
});
                
it('should have a 200 response status', function(done) {
    var response = chakram.get('http://www.google.com/');
    expect(response).to.have.status(200);

    return chakram.wait();
});
```
The output is as follows for both tests (my timeout is increased to 5000 for slow VPN connection speeds): `Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.`

What did work properly for me was the approach in the original comment:
```
it('should have a 200 response status', function(done) {
    var response = chakram.get('http://www.google.com/');
    response.then(function(result) {
        try {
            expect(response).to.have.status(200);
            done();
        }
        catch (e) {
            done(e);
        }
    });
});
```
Which produced this output: `✓ should have a 200 response status (248ms)`.

Any suggestions as to why my setup fails to run in the manner that the example documentation does would be helpful. I have adjusted mine to match that of the first comment (Mocha 2.2.4, chai 2.3.0, chai-as-promised 5.0.0).

**Comment by dareid** [comment]
@twh1808 your first two examples include a done parameter on the 'it' callback function, this can be used to create asynchronous tests. The other method is returning a promise. If you specify a done parameter, the promise is ignored.
So the following should work:
```
it('should have a 200 response status', function() {
    var response = chakram.get('http://www.google.com/');
    return expect(response).to.have.status(200);
});
                
it('should have a 200 response status', function() {
    var response = chakram.get('http://www.google.com/');
    expect(response).to.have.status(200);
    return chakram.wait();
});
```

**Comment by twh1808** [comment]
Wow, so simple... I would not have guessed including `done` as a parameter would have affected that, but clearly it does. Now all of the example tests in my original comment pass with flying colors.

Thanks!

**Comment by dareid** [comment]
I will close this issue, hopefully I have solved your issue. If not, please feel free to reopen.
