### ISSUE TITLE
Post Request and Response with different Content-Type

### ISSUE THREAD

**Issue by akashbulbule** [dareid/chakram#92]
Hello,
I am trying to write a chakram test case to post the body with Content-Type text/plain and expect the success message response, parsed as a JSON (content type : application/json). I tried setting json: false in the POST options, but then the response is not parsed as a JSON. Is there a way in which this can be achieved?

Regards,
Akash

**Comment by dareid** [comment]
Sorry for the late response @akashbulbule. Currently I do not believe so, you would have to manually parse the JSON response in any ascertains.

**Comment by dareid** [comment]
I am going to close this for now as I believe it to be an edge case, if there is more demand for this functionality, please leave a comment
