### ISSUE TITLE
How can I escape a value?

### ISSUE THREAD

**Issue by partounian** [dareid/chakram#93]
For example, I am trying to specify the files1.txt object inside of the files object in the body of a response. 
```javascript
expect(postResponse).to.have.json("files.files1.txt")
```

**Comment by dareid** [comment]
I am a little confused about the question. I think you may be asking how you test an inner property of the returned json. For this the json expectation has a form with two arguments, the first specifies the path. So for example:
```
expect(postResponse).to.have.json("files1.txt", "the value you expect")
```
