### ISSUE TITLE
Headers seem not correctly parsed

### ISSUE THREAD

**Issue by antoine-pous** [dareid/chakram#95]
Hi!

i encounter a strange error when i try to test the headers:

```js
describe("Test server errors", function() {

  it('Should return an error 0x04', function() {

    let res = chakram.get(host + '/v4/path')

    expect(res)
      .to.have.status(401)
      .to.have.header('content-type', 'application/json')
      .to.have.header('charset', 'utf-8')
      .to.comprise.of.json({'error':{'id':'0x04', 'msg':'Authentication required!'}})

    return chakram.wait()
  })

})
```

`AssertionError: expected header content-type with value application/json; charset=utf-8 to match application/json`

I dont understand why the `content-type` expected is `application/json; charset=utf-8` instead of `application/json`

**Comment by dareid** [comment]
Without knowing what your server is responding with, it makes it hard to replicate this. Could you produce an example showing the problem which I could replicate?

From the look of the error message your server is responding with `application/json; charset=utf-8` which does not match your header expectation saying it should be returning `application/json`, hence the error

**Comment by dareid** [comment]
I am going to close this due to inactivity
