### ISSUE TITLE
Is there a way to test an asynchronous API

### ISSUE THREAD

**Issue by mxk1235** [dareid/chakram#96]
our APIs are asynchronous, meaning we create an entity, and then need to wait for it to actually become available.  For example, is there a way to repeatedly hit an endpoint until  it returns a 200 instead of a 404?

thanks in advance!

**Comment by mxk1235** [comment]
i suppose i am asking for the correct way to combine chakram with wait-until https://www.npmjs.com/package/wait-until

**Comment by dareid** [comment]
Any promise based library should be easily built into a chakram test. I found https://www.npmjs.com/package/wait-until-promise which may fit nicely with chakram
