### ISSUE TITLE
I can seem to make the headers work properly. Any help is welcomed

### ISSUE THREAD

**Issue by oscar-mullin** [dareid/chakram#98]
Hi,

I am trying to make a get request after making a post request to get the auth token.

The POST works fine, but when trying to do the get it fails with "Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves."

Any help is appreciated

```javascript
describe("ProofOfConceptLogin", function() {
    it("should get all communities", function () {
		return chakram.post(loginPOSTRequest.url,undefined,loginPOSTRequest.payload)
		.then(function(response){			
			header = {'Authorization':'Bearer ' + response.body.access_token}
			expect(response.response.statusCode).to.equal(200);
			return chakram.get("https://myurltogetdata/elements",{timeout:50000,header: {'Authorization':header}})
			.then(function(response){
				expect(response.response.statusCode).to.equal(200)
			});
		}); 
    });
});

**Comment by zephrose** [comment]
I use a version of this function below for my testing, as I also have to go through an auth layer in our application. The key is pulling the authorization header in response and adding it to the next message. I'm sure this is what you were trying to achieve. I don't perform a POST here, but it should work out the same, as long as you are reading the headers and pulling the key you need.

```
testGetStatusWauth = function(apiRequest, resStatus) {
        it("should return " + resStatus + " on GET request", function () {
        return chakram.request("GET", someAuthEnvURL)
        .then(function(authRes) {
            var authTokenRaw = authRes.body['authToken'];
            var sessionReq = chakram.request("GET", apiRequest, {headers : {'Authorization' : authTokenRaw}});
            return expect(sessionReq).to.have.status(resStatus);
        });
    });
}
```

**Comment by oscar-mullin** [comment]
Hi,

Thanks a lot for the response. I did try changing a bit to map to yours, but still no luck. After some research, the problem seems to be that I was hitting a mocha timeout, not related to chakram. So I just run my test with mocha --timeout 15000 test.js and it works like a charm.

Thanks anyway for taking time to help.
