### ISSUE TITLE
How to configure acceptable response time ?

### ISSUE THREAD

**Issue by 0xbaadf00d** [dareid/chakram#99]
Hello,

Is something I can configure somewhere ?

![image](https://cloud.githubusercontent.com/assets/1005086/26550138/aa9e4cca-447c-11e7-8a17-dbe43757fdb0.png)

Sincerly

**Comment by dareid** [comment]
Hi, this is from mocha the underlying test runner used by Chakram. See https://stackoverflow.com/questions/31975168/why-doesnt-mocha-report-time-for-every-test for ideas in terms of turning off.

**Comment by 0xbaadf00d** [comment]
Thanks
